# Generated by Django 5.1.15 on 2026-09-10 14:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvaloracion',
            name='zona_origen',
            field=models.CharField(blank=True, help_text='Ciudad/zona donde está físicamente el coche (para el transporte).', max_length=60),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='zona_origen',
            field=models.CharField(blank=True, help_text='Ciudad/zona donde está físicamente el coche (para el transporte).', max_length=60),
        ),
        migrations.CreateModel(
            name='HistoricalTarifaTransporte',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('origen', models.CharField(help_text='Zona: "Madrid", "Barcelona"…', max_length=60)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Importe neto (sin IVA).', max_digits=12)),
                ('vigencia_desde', models.DateField(blank=True, null=True)),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tasador.proveedor')),
            ],
            options={
                'verbose_name': 'historical tarifa de transporte',
                'verbose_name_plural': 'historical tarifas de transporte',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TarifaTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(help_text='Zona: "Madrid", "Barcelona"…', max_length=60)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Importe neto (sin IVA).', max_digits=12)),
                ('vigencia_desde', models.DateField(blank=True, null=True)),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas_transporte', to='tasador.proveedor')),
            ],
            options={
                'verbose_name': 'tarifa de transporte',
                'verbose_name_plural': 'tarifas de transporte',
                'ordering': ['proveedor', 'origen'],
            },
        ),
    ]
