# Generated by Django 5.1.15 on 2026-09-10 16:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasador', '0002_historicalvaloracion_zona_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvaloracion',
            name='iva_anuncio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Solo Auto1: el importe de IVA que muestra el anuncio.', max_digits=12),
        ),
        migrations.AddField(
            model_name='tiposubasta',
            name='modo',
            field=models.CharField(choices=[('tabla', 'Tabla por tramos (BCA)'), ('iva_anuncio', 'IVA del anuncio (Auto1)')], default='tabla', max_length=15),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='iva_anuncio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Solo Auto1: el importe de IVA que muestra el anuncio.', max_digits=12),
        ),
    ]
