# Generated by Django 5.1.15 on 2026-09-10 17:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasador', '0003_historicalvaloracion_iva_anuncio_tiposubasta_modo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvaloracion',
            name='precio_salida',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Puja mínima / precio de salida de la subasta.', max_digits=12),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='precio_salida',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Puja mínima / precio de salida de la subasta.', max_digits=12),
        ),
    ]
