# Generated by Django 5.1.15 on 2026-09-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasador', '0004_historicalvaloracion_precio_salida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptofijo',
            name='iva_deducible',
            field=models.BooleanField(default=False, help_text='El importe lleva 21% de IVA que la empresa puede desgravar; el coste real que se usa para la rentabilidad es el neto, no el importe de arriba.'),
        ),
        migrations.AddField(
            model_name='historicalconceptofijo',
            name='iva_deducible',
            field=models.BooleanField(default=False, help_text='El importe lleva 21% de IVA que la empresa puede desgravar; el coste real que se usa para la rentabilidad es el neto, no el importe de arriba.'),
        ),
    ]
