# Generated by Django 5.1.15 on 2026-09-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasador', '0005_conceptofijo_iva_deducible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehiculo',
            name='favorito',
            field=models.BooleanField(db_index=True, default=False, help_text='Marcado para seguirlo de cerca; se mantiene aunque se retase.'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='favorito',
            field=models.BooleanField(db_index=True, default=False, help_text='Marcado para seguirlo de cerca; se mantiene aunque se retase.'),
        ),
    ]
