# Generated by Django 5.1.15 on 2026-09-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasador', '0006_historicalvehiculo_favorito_vehiculo_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehiculo',
            name='mds_modelo',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Market Days Supply: coches iguales en venta ÷ ventas medias/día (últimos 45 días). Dato manual, se puede dejar en blanco.', null=True, verbose_name='MDS modelo'),
        ),
        migrations.AddField(
            model_name='historicalvehiculo',
            name='mds_similar',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Igual que MDS modelo, pero contando coches similares (no idénticos).', null=True, verbose_name='MDS similar'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='mds_modelo',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Market Days Supply: coches iguales en venta ÷ ventas medias/día (últimos 45 días). Dato manual, se puede dejar en blanco.', null=True, verbose_name='MDS modelo'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='mds_similar',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Igual que MDS modelo, pero contando coches similares (no idénticos).', null=True, verbose_name='MDS similar'),
        ),
    ]
