# Generated by Django 5.1.15 on 2026-10-07 13:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasador', '0007_historicalvehiculo_mds_modelo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasadaAuto1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ok', models.BooleanField(default=True)),
                ('revisados', models.PositiveIntegerField(default=0)),
                ('con_cambios', models.PositiveIntegerField(default=0)),
                ('sin_cambios', models.PositiveIntegerField(default=0)),
                ('sin_precio', models.PositiveIntegerField(default=0, help_text='Fichas que ya no muestran precio (¿vendidos?).')),
                ('errores', models.PositiveIntegerField(default=0)),
                ('detalle', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'pasada de seguimiento Auto1',
                'verbose_name_plural': 'pasadas de seguimiento Auto1',
                'ordering': ['-fecha'],
            },
        ),
    ]
