# Generated by Django 5.1.15 on 2026-10-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasador', '0008_pasadaauto1'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvaloracion',
            name='fallos_ficha',
            field=models.PositiveSmallIntegerField(default=0, help_text='Pasadas seguidas en las que la ficha de Auto1 no mostraba precio (al llegar a 2 se marca como vendido).'),
        ),
        migrations.AddField(
            model_name='historicalvaloracion',
            name='ultima_comprobacion',
            field=models.DateTimeField(blank=True, help_text='Última vez que el seguimiento automático miró este coche en Auto1.', null=True),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='fallos_ficha',
            field=models.PositiveSmallIntegerField(default=0, help_text='Pasadas seguidas en las que la ficha de Auto1 no mostraba precio (al llegar a 2 se marca como vendido).'),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='ultima_comprobacion',
            field=models.DateTimeField(blank=True, help_text='Última vez que el seguimiento automático miró este coche en Auto1.', null=True),
        ),
    ]
