# Generated by Django 5.1.15 on 2026-10-08 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasador', '0009_historicalvaloracion_fallos_ficha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioAuto1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_latido', models.DateTimeField(blank=True, null=True)),
                ('programada', models.CharField(blank=True, help_text='Hora diaria de la pasada, p. ej. "08:30".', max_length=5)),
                ('en_curso_desde', models.DateTimeField(blank=True, null=True)),
                ('pasada_solicitada', models.DateTimeField(blank=True, help_text='Pedida desde el Panel; el servicio la recoge.', null=True)),
                ('solicitada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'servicio de seguimiento Auto1',
                'verbose_name_plural': 'servicio de seguimiento Auto1',
            },
        ),
    ]
