# Generated by Django 5.1.15 on 2026-10-08 15:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasador', '0010_servicioauto1'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAuto1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('texto', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'evento del seguimiento Auto1',
                'verbose_name_plural': 'eventos del seguimiento Auto1',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='servicioauto1',
            name='detener_solicitada',
            field=models.BooleanField(default=False, help_text='Pedido de parar la pasada en curso.'),
        ),
        migrations.AddField(
            model_name='servicioauto1',
            name='pausado',
            field=models.BooleanField(default=False, help_text='Si está activo, no hace la pasada diaria automática.'),
        ),
        migrations.AddField(
            model_name='servicioauto1',
            name='problemas',
            field=models.TextField(blank=True, help_text='Problemas de configuración que comunica el servicio.'),
        ),
        migrations.AddField(
            model_name='servicioauto1',
            name='progreso_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicioauto1',
            name='progreso_ref',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='servicioauto1',
            name='progreso_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
