# Generated by Django 5.1.15 on 2026-10-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasador', '0011_eventoauto1_servicioauto1_detener_solicitada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvaloracion',
            name='cierre_auto1',
            field=models.CharField(blank=True, choices=[('no_disponible', 'Ya no está disponible'), ('adjudicado', 'Adjudicado (Vendido)'), ('particular_rechazo', 'El particular no aceptó la oferta')], help_text='Motivo por el que el seguimiento automático dio por cerrado el coche en Auto1. Los cerrados salen de la vista activa pero se conservan.', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalvaloracion',
            name='compra_directa',
            field=models.BooleanField(default=False, help_text='Auto1 lo muestra ahora como Compra Directa (puede volver a subasta).'),
        ),
        migrations.AddField(
            model_name='historicalvaloracion',
            name='precio_compra_directa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='cierre_auto1',
            field=models.CharField(blank=True, choices=[('no_disponible', 'Ya no está disponible'), ('adjudicado', 'Adjudicado (Vendido)'), ('particular_rechazo', 'El particular no aceptó la oferta')], help_text='Motivo por el que el seguimiento automático dio por cerrado el coche en Auto1. Los cerrados salen de la vista activa pero se conservan.', max_length=20),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='compra_directa',
            field=models.BooleanField(default=False, help_text='Auto1 lo muestra ahora como Compra Directa (puede volver a subasta).'),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='precio_compra_directa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
